reuse_api/views.py
# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Request handlers for all endpoints."""

from flask import Blueprint, current_app, render_template, send_file, url_for
from flask_wtf import FlaskForm
from requests import post
from werkzeug.exceptions import HTTPException
from wtforms import BooleanField, StringField, ValidationError
from wtforms.validators import Email, InputRequired

from .models import Repository
from .scheduler import (
    NotARepository,
    determine_protocol,
    schedule_if_new_or_later,
)


# Blueprint for all endpoints delivering human-readable HTML/SVG content
html_blueprint = Blueprint("html", __name__)

# Blueprint for all endpoints delivering machine-readable JSON content
json_blueprint = Blueprint("json", __name__)

# Start page
@html_blueprint.route("/")
def index():
    compliant_repos = Repository.projects().total
    return render_template("index.html", compliant_repos=compliant_repos)


# Filter for a project URL
def sanitize_project_url(data):
    if data is not None:
        p = data.find("://")
        if p != -1:
            data = data[p + 3 :]  # noqa
        if data.lower().endswith(".git"):
            data = data[:-4]
    return data


# Validation of a project URL
def validate_project_url(form, field):
    try:
        determine_protocol(field.data)
    except NotARepository:
        raise ValidationError("Not a Git repository")
    if Repository.is_registered(field.data):
        info_page = url_for(
            "html.info", url=field.data, _external=True, _scheme="https"
        )
        info_page_url = f'<a href="{info_page}">here</a>'
        raise ValidationError(
            f"Project is already registered. See its REUSE status {info_page_url}."
        )


# Registration form
class RegisterForm(FlaskForm):
    name = StringField(label="Your name", validators=[InputRequired()])
    confirm = StringField(
        label="Your email",
        description=(
            "We need your email address to contact you in case of important "
            "changes to this service. If you would like to be informed about "
            "important updates on REUSE and the FSFE, please tick the "
            "optional box further down."
        ),
        validators=[InputRequired(), Email()],
    )
    project = StringField(
        label="Your project URL",
        description=(
            "Please add your project URL without a schema like http:// or "
            "git://. We automatically try git, https, and http as schemas."
        ),
        filters=[sanitize_project_url],
        validators=[InputRequired(), validate_project_url],
    )
    wantupdates = BooleanField(
        label=(
            "I want to receive occasional information about REUSE and other "
            "FSFE activities"
        )
    )


@html_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        params = {"appid": "reuse-api", **form.data}
        del params["csrf_token"]
        response = post(
            url=current_app.config["FORMS_URL"],
            data=params,
            allow_redirects=False,
        )
        if not response.ok:
            return response.text, response.status_code
        return render_template("register-success.html", **form.data)
    return render_template("register.html", form=form)


@html_blueprint.route("/badge/<path:url>")
def badge(url):
    row = schedule_if_new_or_later(url, current_app.scheduler)

    if row is None:
        status = "unregistered"
    else:
        current_app.logger.debug(f"sending badge for '{row.url}'")
        status = row.status

    result = send_file(f"badges/{status}.svg", mimetype="image/svg+xml")

    # Disable caching for badge files
    result.cache_control.max_age = 0
    result.cache_control.must_revalidate = True
    result.cache_control.no_cache = True
    result.cache_control.no_store = True
    result.cache_control.private = True
    result.cache_control.public = False
    result.headers["Expires"] = "Thu, 01 Jan 1970 00:00:00 UTC"

    return result


@html_blueprint.route("/info/<path:url>")
def info(url):
    row = schedule_if_new_or_later(url, current_app.scheduler)

    if row is None:
        return render_template("unregistered.html", url=url), 404

    return render_template(
        "info.html",
        url=row.url,
        project_name="/".join(row.url.split("/")[-2:]),
        hash=row.hash,
        status=row.status,
        lint_code=row.lint_code,
        lint_output=row.lint_output,
        last_access=(
            row.last_access.strftime("%d %b %Y %X")
            if row.last_access
            else None
        ),
        badge=url_for(
            "html.badge", url=row.url, _external=True, _scheme="https"
        ),
        info=url_for(
            "html.info", url=row.url, _external=True, _scheme="https"
        ),
        json=url_for(
            "json.status", url=row.url, _external=True, _scheme="https"
        ),
    )


# Return error messages in JSON format
@json_blueprint.errorhandler(HTTPException)
def handle_error(err):
    return {"error": err.description}, err.code


@json_blueprint.route("/status/<path:url>")
def status(url):
    row = schedule_if_new_or_later(url, current_app.scheduler)

    if row is None:
        return {"url": url, "status": "unregistered"}

    # Return the current entry in the database.
    return {
        "url": row.url,
        "hash": row.hash,
        "status": row.status,
        "lint_code": row.lint_code,
        "lint_output": row.lint_output,
        "last_access": row.last_access.isoformat()
        if row.last_access
        else None,
        "badge": url_for(
            "html.badge", url=row.url, _external=True, _scheme="https"
        ),
    }


@html_blueprint.route("/projects")
@html_blueprint.route("/projects/page/<int:page>")
def projects(page=1):
    registered_list = Repository.projects(page)
    return render_template("projects.html", registered_list=registered_list)

reuse_api/templates/index.html
{% extends "base/base.html" %}

{% block title %}REUSE API - Easy REUSE compliance check{% endblock %}

{% block content %}
  <h1 class="title"><strong>REUSE</strong> API</h1>
  <p class="lead intro">
    Welcome to the REUSE API. This service helps you to continuously
    check and display compliance with the REUSE guidelines. REUSE makes
    licensing easy for humans and machines alike. Register your project
    with us, make it REUSE compliant, and get your compliant badge
    today!
  </p>

  <p class="lead intro">
    If you are not sure what REUSE is, please head to <a
    href="https://reuse.software">our main page</a> first.
  </p>

  <h2>Check your project</h2>

  <p>
    We offer a <a href="https://reuse.software/dev/">wide set of
    tools</a> to support you in adopting REUSE for your project. As a
    supplement, this API checks the REUSE compliance status for you.
    You can include a badge indicating the live status in your README
    file, and parse the output using the generated JSON file.
  </p>

  <p>
    All it takes is a registration of your project with this service.
    <a href="/register">Sign up</a>, confirm your email, and see the
    output. Join the <strong>{{ compliant_repos }}</strong> other
    <a href="/projects">registered compliant repositories</a> today!
  </p>

  <div class="row vertical-align">

    <div class="col-sm-8">

      <h2>What is REUSE?</h2>

      <p>
        Copyright and licensing is difficult, especially when reusing
        software from different projects that are released under
        various different licenses. REUSE was started by the <a
        href="https://fsfe.org">Free Software Foundation Europe
        (FSFE)</a> to provide a set of recommendations to make
        licensing your Free Software projects easier. Not only do these
        recommendations make it easier for you to declare the licenses
        under which your works are released, but they also make it
        easier for a computer to understand how your project is
        licensed.
      </p>

    </div>

    <div class="reuse-logo col-sm-4">
      <img src="{{url_for('static', filename='img/reuse.png')}}" alt="Logo of REUSE">
    </div>

  </div>

  <h2>Troubleshooting</h2>

  <p>
    When using this service, you might run into some commonly asked
    questions. If yours is not answered here, please <a
    href="https://git.fsfe.org/reuse/api/issues">open an issue</a> or
    get in touch with the <a
    href="https://lists.fsfe.org/mailman/listinfo/reuse">REUSE
    community</a>.
  </p>

  <p>
    <ul>
      <li>
        <strong>Which version control systems are supported?</strong><br />
        Currently, this service only supports Git. However, the underlying
        helper tool can be used for multiple systems. Please refer to <a
        href="https://reuse.software/faq/#no-git">our FAQ section</a> for more
        information.
      </li>
      <li>
        <strong>Which code hosting platforms are supported?</strong><br />
        As long as it is Git, we strive to support all platforms. We
        value decentralisation, so you will also be able to connect
        your own instance to our service. If yours does not work,
        please open an issue in our <a
        href="https://git.fsfe.org/reuse/api">project repo</a>.
      </li>
      <li>
        <strong>Can I register multiple projects?</strong><br />
        Yes, but please do not abuse our service and only register the
        projects you actually care for. We are a charitable non-profit
        organisation and have limited server capacities. Also, please
        make sure to register and confirm your projects one-by-one.
      </li>
      <li>
        <strong>Are private repositories supported?</strong><br />
        No, but users who want to check the status of their private
        repos can <a href="https://reuse.software/dev/#ci">include the
        REUSE linter in their CI/CD processes</a>. If you would like to
        help us extend this service, you are welcome to check out the
        <a href="https://git.fsfe.org/reuse/api">code on our Git
        platform</a>.
      </li>
      <li>
        <strong>Which branches are checked?</strong><br />
        We only check the main branch when cloning your repository.
        This service does not support checking other branches
        currently. However, you can <a
        href="https://reuse.software/dev/#ci">include the REUSE helper
        tool in your CI/CD processes</a> to achieve that during your
        development.
      </li>
      <li>
        <strong>Why do you need my email for registration?</strong><br />
        The REUSE API is a new service under continuous development. We
        would like to contact you if we need to introduce some breaking
        changes (which we will try to avoid of course). You will also
        be able to receive additional information about REUSE if you
        like.
      </li>
      <li>
        <strong>I want to change/delete my project here.</strong><br />
        If you want your project to be deleted here or have it changed
        (e.g. with a different address), please <a
        href="https://fsfe.org/contact">contact us</a>. But please be
        aware that anyone else can add your project again with their
        email address as long as it is a valid and accessible Git
        repository.
      </li>
      <li>
        <strong>Can I see and reuse your code?</strong><br />
        Of course. The API's source code is <a
        href="https://git.fsfe.org/reuse/api">available under Free
        Software licenses</a>. Obviously, it is <a
        href="https://api.reuse.software/info/git.fsfe.org/reuse/api">REUSE
        compliant</a>.
      </li>
    </ul>
  </p>

{% endblock %}

reuse_api/templates/info.html
{% extends "base/base.html" %}

{% block title %}{{project_name}} | REUSE API{% endblock %}

{% block content %}
    <h1>REUSE compliance of {{project_name}}</h1>
    {% if status == "checking" %}
    <p>
      The initial check for REUSE compliance has not yet been finished.
      Please refresh the page in a few seconds.
    </p>
    {% else %}
    <p class="lead">
      {% if status == "compliant" %}
      Congratulations, <em>{{url}}</em> is REUSE compliant! This
      project adopts <a href="https://reuse.software/">the
      recommendations</a> to make software licensing easy for humans
      and machines alike.
      {% elif status == "non-compliant" %}
      Unfortunately, <em>{{url}}</em> is <strong>not</strong> REUSE
      compliant and does not fully adopt <a
      href="https://reuse.software/">the recommendations</a> to make
      software licensing easy for humans and machines alike. Have a
      look at <a href="https://reuse.software/tutorial">our
      tutorial</a> to learn about the three simple steps to become
      REUSE compliant.
      {% endif %}
    </p>

    <h2>Badge</h2>
    <p>
      <img src="{{badge}}"/>
    </p>
    <p>
      To add the badge to your project's <code>README.md</code> file,
      use the following snippet:
    </p>
    <pre>[![REUSE status]({{badge}})]({{info}})</pre>

    <h2>Parseable JSON</h2>
    <p>
      All information about the latest compliance check can also be
      accessed via a <a href="{{json}}">machine-parsable JSON file</a>.
    </p>

    <h2>Last lint output</h2>
    <p>
      Commit <code>{{hash}}</code> was checked on {{last_access}} UTC
      with the following result:
    </p>
    <pre class="pre-scrollable">{{lint_output}}</pre>
    {% endif %}

{% endblock %}

reuse_api/templates/projects.html
{% extends "base/base.html" %}

{% block title %}Compliant projects | REUSE API{% endblock %}

{% block content %}
<div class="table-responsive">
  <h1>Compliant Projects</h1>

  <p class="lead">
    Of all repositories registered with this service, {{ registered_list.total }} are
    successfully following the REUSE best practices. You can view them below,
    sorted by their last check.
  </p>

  <table class="table table-striped registered">
    <tr>
      <th>
        Repository URL
      </th>
      <th>
        Details
      </th>
      <th>
        Repository
      </th>
    </tr>
    {%  for project in registered_list.items %}
      <tr>
        <td>
          {{ project.url }}
        </td>
        <td>
          <a href="/info/{{ project.url }}"><i class="fas fa-info-circle"></i></a>
        </td>
        <td>
          <a href="https://{{ project.url }}" target="_blank"><i class="fas fa-external-link-alt"></i></a>
        </td>
      </tr>
    {% endfor %}
      <tr>
        <td></td>
        <td>
          {% if registered_list.has_prev %}
            <a href="{{ url_for('html.projects', page=registered_list.prev_num) }}">Previous</a>
          {% endif %}
        </td>
        <td>
          {% if registered_list.has_next %}
            <a href="{{ url_for('html.projects', page=registered_list.next_num) }}">Next</a>
          {% endif %}
        </td>
      </tr>
    </table>
  </div>
{% endblock %}

reuse_api/templates/register-success.html
{% extends "base/base.html" %}

{% block title %}Registration successful | REUSE API{% endblock %}

{% block content %}
  <h1>Registration successful</h1>
  <p>
    Thank you for registering {{project}} for the REUSE API. Please
    check your email for further steps.
  </p>

{% endblock %}

reuse_api/templates/register.html
{% macro render_field(field, before="", after="", placeholder="") %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    {{field.label(class="col-sm-2 control-label")}}
    <div class="col-sm-5">
      {% if before or after %}
        <div class="input-group">
      {% endif %}
      {% if before %}
        <span class="input-group-addon">{{before}}</span>
      {% endif %}
      {{field(class="form-control", placeholder=placeholder)}}
      {% if after %}
        <span class="input-group-addon">{{after}}</span>
      {% endif %}
      {% if before or after %}
        </div>
      {% endif %}
      {% if field.errors %}
        <ul class="col-sm-offset-2 list-unstyled help-block">
          {% for error in field.errors %}
            <li><strong>{{error|safe}}</strong></li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="col-sm-5 small">
      {{field.description}}
    </div>
  </div>
{% endmacro %}

{% extends "base/base.html" %}

{% block title %}Register a project | REUSE API{% endblock %}

{% block content %}

    <h1>Register a project</h1>

    <form class="form-horizontal" action="" method="post">
      {{form.csrf_token}}
      {{render_field(form.name)}}
      {{render_field(form.confirm)}}
      {{render_field(
        form.project,
        before="git://",
        after=".git",
        placeholder="gitserver.com/user/repo"
      )}}
      <div class="form-group">
        <div class="checkbox col-sm-offset-2 col-sm-5">
          <label>
            {{form.wantupdates}} {{form.wantupdates.label}}
          </label>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-4">
          <button type="submit" class="btn btn-primary btn-lg">Register</button>
        </div>
      </div>
    </form>

{% endblock %}

reuse_api/templates/unregistered.html
{% extends "base/base.html" %}

{% block title %}Project not registered | REUSE API{% endblock %}

{% block content %}
  <h1>Project not registered</h1>
  <p class="lead">
    Your requested project <em>{{url}}</em> is not registered with this
    service.
  </p>

  <p>
    Please register your project <a href="/register">here</a> to enable
    the automatic checks.
  </p>

{% endblock %}